### ISSUE TITLE
Add Milestone and Task models and routes

### ISSUE THREAD

**Issue by polley** [JitaIO/jita-community-edition#14]
- [x] Milestone route
- [x] Milestone scheme file
- [x] Milestone resolver file
- [x] Milestone controller file
- [x] Task route
- [x] Task scheme file
- [x] Task resolver file
- [x] Task controller file

**Comment by polley** [comment]
Task completed

**Comment by polley** [comment]
- [ ] Replaced ID with UUID
- [ ] Added basic fields like "created_date" and "last_updated" to every model

**Comment by polley** [comment]
### Deleting old nodes if necessary 

```
MATCH (n) DETACH DELETE n
```

### The following graph can test this stage of the code

```
MATCH (n) DETACH DELETE n;

CREATE (TheMatrix:Project {UUID: "33c7167f-39c1-4ca7-96ab-3201dd2899b6", title:'The Matrix', released:1999, tagline:'Welcome to the Real World', created_date: datetime(), last_edited: datetime()})
CREATE (Keanu:User {UUID: "89934b07-d120-4745-aff3-f7215abf8a8a", name:'Keanu Reeves', email: 'keanu.reeves@gmail.com', born:1964, created_date: datetime(), last_edited: datetime()})
CREATE (Carrie:User {UUID: "59a35525-628e-461b-9a2d-c2aff538e525", name:'Carrie-Anne Moss', email: 'carie.anne.moss@gmail.com', born:1967, created_date: datetime(), last_edited: datetime()})
CREATE (Laurence:User {UUID: "25be827b-a096-47a7-a46c-9c3bb433834f", name:'Laurence Fishburne', email: 'laurence.fishburne@gmail.com', born:1961, created_date: datetime(), last_edited: datetime()})
CREATE (Hugo:User {UUID: "767e2b3f-fe36-4c83-8da4-1df450b2bf07", name:'Hugo Weaving', email: 'hugo.weaving@gmail.com', born:1960, created_date: datetime(), last_edited: datetime()})
CREATE
(Keanu)-[:IS_IN {roles:['Neo']}]->(TheMatrix),
(Carrie)-[:IS_IN {roles:['Trinity']}]->(TheMatrix),
(Laurence)-[:IS_IN {roles:['Morpheus']}]->(TheMatrix),
(Hugo)-[:IS_IN {roles:['Agent Smith']}]->(TheMatrix)

CREATE (Emil:User {UUID: "dec35e23-d6b5-4f35-8004-4ca1d4051fd0", name:"Emil Eifrem", born:1978, email: 'emil.eifrem@gmail.com', created_date: datetime(), last_edited: datetime()})
CREATE (Emil)-[:IS_IN {roles:["Emil"]}]->(TheMatrix)

CREATE (TheMatrixReloaded:Project {UUID: "1887d93c-bb80-4c7f-be6a-be82b8edd179", title:'The Matrix Reloaded', released:2003, tagline:'Free your mind', created_date: datetime(), last_edited: datetime()})
CREATE
(Keanu)-[:IS_IN {roles:['Neo']}]->(TheMatrixReloaded),
(Carrie)-[:IS_IN {roles:['Trinity']}]->(TheMatrixReloaded),
(Laurence)-[:IS_IN {roles:['Morpheus']}]->(TheMatrixReloaded),
(Hugo)-[:IS_IN {roles:['Agent Smith']}]->(TheMatrixReloaded);

MATCH (p:Project {title:"The Matrix"}), (neo:User{name: "Keanu Reeves"}) CREATE (p)-[:HAS]->(ms:Milestone {UUID: "ada5b99d-eed7-4d21-8b99-9531880ff430", name: "A milestone", deadline: datetime(), created_date: datetime(), last_edited: datetime()})-[:HAS]->(t:Task{UUID: "b2eb15a1-68db-4405-a239-1ffcc3e873e0", name: "A special task", deadline: datetime(), created_date: datetime(), last_edited: datetime()})-[:ASSIGNED_TO]->(neo);
```
